### ISSUE TITLE
Playground Throws Error On Valid Query and Mutation

### ISSUE THREAD

**Issue by zach-is-my-name** [graphcool/console#999]
As discussed with Nilan:

http://imgur.com/fxwtZwI

> mutation {
> createGoalDoc(goal: "TestGoal4") {
> goal
> }
> }
> 
> type GoalDoc implements Node {
> createdAt: DateTime!
> id: ID! @isUnique
> updatedAt: DateTime!
> goal: String
> steps: [String!]
> }

I'm producing GraphQL errors on valid queries as well 
http://imgur.com/5d9tkJC

Flow is : Schema > Playground > [enter query] Tooltip Error > Execute > Valid Query Result Returned) OR Schema > Playground > [enter query] Error Tooltip > Refresh > No Tool Tip Error > Execute > Valid Query Result

For what it's worth, this happened after changing Type name with confirmation...
A refresh or 'Pretifying' eliminates the error tooltip

**Comment by marktani** [comment]
Hey @zach-is-my-name, can you try again? This should be fixed now 🙂

**Comment by zach-is-my-name** [comment]
I'm sorry still experiencing it:

Steps:
1. Emptied cache
2. Logout 
3. Login
4. Enter Query
5. Error despite Valid Return 

http://imgur.com/JyV067A

**Comment by timsuchanek** [comment]
Hey @zach-is-my-name first of all thanks for taking the time to check it again!
I guess emptying the cache is not helping. (it's the application cache with cookies etc.)
What should help instead is opening the dev tools and doing a "Hard Reload" with `cmd+shift+r`.

Sorry for the trouble and thanks for your help!

**Comment by zach-is-my-name** [comment]
It's now fixed.  Thank you for taking the time to improve this amazing product.
